# Generated by Django 5.1.7 on 2025-04-01 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.AddField(
            model_name='food',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
