# Generated by Django 5.1.7 on 2025-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeal',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
